# Generated by Django 3.2 on 2021-05-02 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210430_1957'),
    ]

    operations = [
        migrations.AddField(
            model_name='cases',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='tasks',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
