# Generated by Django 3.2 on 2021-05-02 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210502_1402'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funnels',
            name='title',
        ),
    ]
